#!/bin/sh

echo "Searching for dependencies for `basename $1`..."

cat ${MODULE_PATH}/../modules.dep | grep "`basename $1`: " | awk '{$1= ""; print $0}' | tr ' ' '\n' | grep -v '^$' | while read moddeppath;
do
	[ -d `dirname ${BUILD_DIR}/${moddeppath}` ] || mkdir -p `dirname ${BUILD_DIR}/${MODULE_PATH}/../${moddeppath}`;
	[ -f ${BUILD_DIR}/${MODULE_PATH}/../${moddeppath} ] ||
		(
			cp -a ${MODULE_PATH}/../${moddeppath} ${BUILD_DIR}/${MODULE_PATH}/../${moddeppath};
			echo "Imported `basename $1` dependency `basename /${moddeppath}`";
			MODULE_PATH=${MODULE_PATH} BUILD_DIR=${BUILD_DIR} ./scripts/import-dependencies ${moddeppath};
		)
done
