#!/bin/sh

/bin/busybox mount -t proc none /proc || echo "Error mounting /proc filesystem"
/bin/busybox mount -t sysfs none /sys || echo "Error mounting /sys filesystem"

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/ceres/sbin

/bin/busybox --install -s || error busybox

/etc/init.d/rcS || echo "Error running init.d/rcS"

echo "Setting hostname to ceres-c${CON}"
hostname ceres-c${CON}

echo "Starting getty on tty${CONTTY}"
exec getty -L 0 tty${CONTTY} &
