#!/bin/sh

/bin/busybox --install -s || echo "Error configuring busybox"

export PATH=/sbin:/usr/sbin:/bin:/usr/bin:/opt/ceres/sbin

mount -t proc none /proc || echo "Error mounting /proc filesystem"
mount -t sysfs none /sys || echo "Error mounting /sys filesystem"

/etc/init.d/rcS || echo "Error running init.d/rcS"

echo "Setting hostname to ceres-c${CON}"
hostname ceres-c${CON}

echo "Starting getty on tty${CONTTY}"
while true; do getty -L 0 tty${CONTTY}; clear; done
