#!/bin/busybox sh

/bin/busybox --install -s

error() {
	echo ''
	echo '  Error mounting the $1 filesystem.'
	echo ''
	echo '  You will be dropped to a rescue shell. Examine'
	echo '  the output of "dmesg" to see what went wrong.'
	echo ''
	echo '  To continue boot, type "exit".'
	echo ''
	sh
}

if [ -d /lib/modules/`uname -r` ];
then
	depmod -a
	modprobe -l | while read line; do modprobe `basename $line ".ko"`; done
fi

mount -t proc none /proc || error proc
mount -t sysfs none /sys || error sys
mount -t devtmpfs none /dev || error dev

echo 0 > /proc/sys/kernel/printk
clear

echo "                          "
echo "   ___ ___ _ __ ___  ___  "
echo "  / __/ _ \ '__/ _ \/ __| "
echo " | (_|  __/ | |  __/\__ \ "
echo "  \___\___|_|  \___||___/ "
echo "                          "
echo "      ceres.github.io     "
echo "                          "

mkdir -p /boot && \
	mount -t ext4 -o rw /dev/sda1 /boot || error boot
mkdir -p /mnt/squashfs && \
	mount -t squashfs -o ro /dev/sda2 /mnt/squashfs || error squashfs
mkdir -p /mnt/persist && \
	mount -t ext4 -o rw /dev/sda3 /mnt/persist || error persistent

mkdir -p /mnt/overlay/control &&
	mkdir -p /mnt/persist/fs_control && \
	mkdir -p /mnt/persist/work_control && \
	mount -t overlay overlay -o lowerdir=/mnt/squashfs,upperdir=/mnt/persist/fs_control,workdir=/mnt/persist/work_control /mnt/overlay/control || error overlay

mkdir -p /mnt/persist/fs_container1
mkdir -p /mnt/persist/fs_container2
mkdir -p /mnt/persist/fs_container3

for container in /mnt/persist/fs_container*;
do
	export CON=$(echo ${container} | grep -Eo '[0-9]+$')
	export CONTTY=$((${CON}+1))

	mkdir -p /mnt/persist/work_container${CON}
	mkdir -p /mnt/overlay/container${CON}

	mount -t overlay overlay -o lowerdir=/mnt/overlay/control,upperdir=/mnt/persist/fs_container${CON},workdir=/mnt/persist/work_container${CON} /mnt/overlay/container${CON} || error overlay

	echo "Starting container ${CON}, press Alt-F${CONTTY} to access"

	mkdir -p /mnt/overlay/container${CON}/proc
	mkdir -p /mnt/overlay/container${CON}/sys
	mkdir -p /mnt/overlay/container${CON}/dev

	# mount -o bind /dev /mnt/overlay/container${CON}/dev || error dev

	cp /cinit /mnt/overlay/container${CON}/init
	mkdir -p /var/namespaces
	/bin/busybox chroot /mnt/overlay/container${CON} /usr/bin/unshare \
		-C=/var/namespaces/${CON}.cgr \
		-u=/var/namespaces/${CON}.uts \
		-i=/var/namespaces/${CON}.ipc \
		-n=/var/namespaces/${CON}.net \
		-p=/var/namespaces/${CON}.pid \
		-m=/var/namespaces/${CON}.mnt \
		-f /init > /dev/tty${CONTTY} &
done

umount /proc
umount /sys

echo ""
echo "Welcome to the ceres-control console."

hostname ceres-control
mount -o bind /dev /mnt/overlay/control/dev
exec switch_root /mnt/overlay/control /bin/busybox sh -c '
	mount -t proc none /proc
	mount -t sysfs none /sys
	while true; do getty -L 0 console; done
'
