#!/bin/busybox sh

/bin/busybox --install -s

error() {
	echo ''
	echo '  Error mounting the $1 filesystem.'
	echo ''
	echo '  You will be dropped to a rescue shell. Examine'
	echo '  the output of "dmesg" to see what went wrong.'
	echo ''
	echo '  To continue boot, type "exit".'
	echo ''
	sh
}

if [ -d /lib/modules/`uname -r` ];
then
	depmod -a
	modprobe -l | while read line; do modprobe `basename $line ".ko"`; done
fi

mount -t proc none /proc || error proc
mount -t sysfs none /sys || error sys
mount -t devtmpfs none /dev || error dev

echo 0 > /proc/sys/kernel/printk
clear

echo "                          "
echo "   ___ ___ _ __ ___  ___  "
echo "  / __/ _ \ '__/ _ \/ __| "
echo " | (_|  __/ | |  __/\__ \ "
echo "  \___\___|_|  \___||___/ "
echo "                          "
echo "      ceres.github.io     "
echo "                          "

mkdir -p /boot && \
	mount -t ext4 -o rw /dev/sda1 /boot || error boot
mkdir -p /mnt/squashfs && \
	mount -t squashfs -o ro /dev/sda2 /mnt/squashfs || error squashfs
mkdir -p /mnt/persist && \
	mount -t ext4 -o rw /dev/sda3 /mnt/persist || error persistent

mkdir -p /mnt/persist/fs_1
mkdir -p /mnt/persist/fs_2
mkdir -p /mnt/persist/fs_3

for container in /mnt/persist/fs*;
do
	export CON=$(echo ${container} | grep -Eo '[0-9]+$')
	export CONTTY=$((${CON}+1))

	mkdir -p /mnt/persist/work_${CON}
	mkdir -p /mnt/overlay/container_${CON}

	mount -t overlay overlay -o lowerdir=/mnt/squashfs,upperdir=/mnt/persist/fs_${CON},workdir=/mnt/persist/work_${CON} /mnt/overlay/container_${CON} || error overlay

	echo "Starting container ${CON}, press Alt-F${CONTTY} to access"

	mkdir -p /mnt/overlay/container_${CON}/proc
	mkdir -p /mnt/overlay/container_${CON}/sys
	mkdir -p /mnt/overlay/container_${CON}/dev

	# mount -o bind /dev /mnt/overlay/container_${CON}/dev || error dev

	cp /cinit /mnt/overlay/container_${CON}/init
	/bin/busybox chroot /mnt/overlay/container_${CON} /usr/bin/unshare -Cuinpfm /init > /dev/tty${CONTTY} &
done

umount /dev
umount /proc
umount /sys

echo ""
echo "Welcome to the ceres-control console."

hostname ceres-control
exec switch_root /mnt/squashfs /init
