#!/bin/busybox sh

/bin/busybox --install -s

error() {
	echo ''
	echo '  Error mounting the $1 filesystem.'
	echo ''
	echo '  You will be dropped to a rescue shell. Examine'
	echo '  the output of "dmesg" to see what went wrong.'
	echo ''
	echo '  To continue boot, type "exit".'
	echo ''
	sh
}

if [ -d /lib/modules/`uname -r` ];
then
	depmod -a
	modprobe -l | while read line; do modprobe `basename $line ".ko"`; done
fi

mount -t proc none /proc || error proc
mount -t sysfs none /sys || error sys
mount -t devtmpfs none /dev || error dev

echo 0 > /proc/sys/kernel/printk
clear

echo "                          "
echo "   ___ ___ _ __ ___  ___  "
echo "  / __/ _ \ '__/ _ \/ __| "
echo " | (_|  __/ | |  __/\__ \ "
echo "  \___\___|_|  \___||___/ "
echo "                          "
echo "      ceres.github.io     "
echo "                          "

mkdir -p /boot && \
	mount -t ext4 -o rw /dev/sda1 /boot || error boot
mkdir -p /mnt/squashfs && \
	mount -t squashfs -o ro /dev/sda2 /mnt/squashfs || error squashfs
mkdir -p /mnt/persist && \
	mount -t ext4 -o rw /dev/sda3 /mnt/persist || error persistent
	
mkdir -p /mnt/persist/container_1
mkdir -p /mnt/persist/container_2
mkdir -p /mnt/persist/container_3
	
for container in /mnt/persist/container*;
do
	CON=$(echo ${container} | grep -Eo '[0-9]+$')
	TTY=$((${CON}+1))
	mkdir -p ${container}_fs ${container}_work ${container}_overlay && \
		mount -t overlay -o lowerdir=/mnt/squashfs,upperdir=${container}_fs,workdir=${container}_work overlay ${container}_overlay || error overlay
	echo "Starting container ${CON} on tty${TTY}..."
	/usr/bin/unshare -Cuinpfm /bin/busybox chroot ${container}_overlay /sbin/init > /dev/tty${TTY} || sh &
	echo "Started container ${CON}"
done

exec switch_root /overlay /sbin/getty 0 console
